### ISSUE TITLE
`luarocks install magic` on Mac OS X

### ISSUE THREAD

**Issue by gingerbeardman** [josefnpat/pico8utils#2]
```
Matts-iMac:carts matt$ luarocks install magick

Error: No results matching query were found.
```

Any ideas?

**Comment by josefnpat** [comment]
Hey @gingerbeardman 

What version of luarocks are you using?

[magick has a dependency of luajit/lua 5.1 (not 5.2)](https://luarocks.org/modules/leafo/magick)

You may have to tell luarocks to install the 5.1 version.

Please tell me if this works or not, this would be something nice to have in the readme.

**Comment by gingerbeardman** [comment]
I'm running 5.3

I only wanted to use your tool for export/import PNG which I now realise Pico8 has built in.

**Comment by josefnpat** [comment]
@gingerbeardman yeah - it does make that tool rather moot - I'll have to see if I can refactor the script to use the pico8 binary, otherwise remove it from this repo.

**Comment by FranciscoE-Hudl** [comment]
Solution described in https://github.com/josefnpat/pico8utils/issues/3
