### ISSUE TITLE
Exception in v0.1.6 cartridges

### ISSUE THREAD

**Issue by FranciscoE-Hudl** [josefnpat/pico8utils#4]
Installation as in https://github.com/josefnpat/pico8utils/issues/3

For input file

http://www.lexaloffle.com/bbs/cposts/2/20068.p8.png

```
Usage:  pico2png.lua [FILE.png] [TARGET.p8]
__gfx__
luajit: ./png2pico.lua:69: Error: Input image contains invalid color
stack traceback:
    [C]: in function 'assert'
    ./png2pico.lua:69: in main chunk
    [C]: at 0x0100002150
```

**Comment by josefnpat** [comment]
the `pico2png.lua` file converts `*.p8` files, not `*.p8.png`. The `.p8.png` contains the `.p8` data in the alpha layer I believe, but I never dug into it to figure out how.

The conversion of `*.p8.png` to `*.p8` is included in the `pico8` binary, so I think it might be superfluous to add it as a script - but I would be very happy to accept a PR for a `picopng2png.lua` script and a `pico2picopng.lua` script, even if it was dependent on `pico8`

**Comment by FranciscoE-Hudl** [comment]
hahaha my mistake then, apologies.

I'm working around the tooling, but haven't used the actual interpreter yet.
